# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:12.16.2

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

pages:
  cache:
    paths:
    - node_modules/
  stage: deploy
  script:
    - npm install --global
    - npm install --global @angular/cli@9.1.1
    - npm install --save-dev @angular-devkit/build-angular@0.901.1
    - ng build
  artifacts:
   paths:
     - public
  only:
    - master
    - pages
   

